"""
GitLab 用户名单 — 以 Excel 中用户更新的记录为准
来源: 【交付HK】BSMS项目整体进度计划 (更新中)20260702备份_new.xlsx → 用户名单 sheet
更新时间: 2026-07-02
"""

GITLAB_USERS = [
    # 组别, 中文名, GitLab ID, username, GitLab name, 备注
    ("系统开发组（后端）", "邱靖凯", 10, "qiujingkai", "Qiu JingKai", ""),
    ("系统开发组（后端）", "欧军豪", 13, "ezio", "Ou Junhao", ""),
    ("系统开发组（后端）", "肖文浩", 23, "xiaowenhao", "Xiao WenHao", ""),
    ("系统开发组（后端）", "潘智豪", 8, "panzhihao", "Pan ZhiHao", ""),
    ("系统开发组（后端）", "徐学凤", 5, "xuxf", "Xu Xuefeng", ""),
    ("系统开发组（后端）", "钟浩锋", 9, "zhonghaofeng", "Zhong HaoFeng", ""),
    ("系统开发组（后端）", "蔡晓钰", 48, "caixy", "Cai Xiaoyu", ""),
    ("系统开发组（后端）", "陈丽霞", 66, "chenlx", "Chen Lixia", ""),
    ("系统开发组（后端）", "郑宝华", 70, "zhengbh", "Zheng Baohua", ""),
    ("系统开发组（后端）", "邓康", 81, "dengkang", "Deng Kang", ""),
    ("系统开发组（后端）", "何奎", 3, "hek", "He Kui", ""),
    ("系统开发组（前端）", "池一帆", 17, "chiyifan", "Chi YiFan", ""),
    ("系统开发组（前端）", "张永辉", 14, "zhangyonghui", "Zhang YongHui", ""),
    ("系统开发组（前端）", "张映杰", 11, "zhangyingjie", "Zhang YingJie", ""),
    ("系统开发组（前端）", "丁传琨", 39, "dingchuankun", "Ding ChuanKun", ""),
    ("系统开发组（前端）", "蔡骁聪", 15, "caixc", "Cai Xiaocong", ""),
    ("系统开发组（前端）", "许崇楠", 50, "xuchongnan", "Xu ChongNan", ""),
    ("系统开发组（前端）", "姚川", 51, "yaoc", "Yao Chuan", ""),
    ("系统开发组（前端）", "林河", 16, "linh", "Lin He", ""),
    ("系统开发组（前端）", "刘浩龙", 64, "liuhaolong", "Liu HaoLong", ""),
    ("系统开发组（前端）", "李术扬", 4, "lishuyang", "Li ShuYang", ""),
    ("质量测试组", "陈俊宇", 18, "chenjunyu", "Chen JunYu", ""),
    ("质量测试组", "梁曜显", 35, "liangyaoxian", "Liang YaoXian", ""),
    ("质量测试组", "黄泽悦", 29, "huangzeyue", "Huang ZeYue", ""),
    ("质量测试组", "杨行", 30, "yanghangh", "Yang Hang2024", ""),
    ("质量测试组", "杨涵", 49, "yangh", "Yang Han", ""),
    ("其他", "系统管理员", 1, "root", "Administrator", ""),
    ("其他", "李泽桦", 26, "lizehua1", "Li Zehua", ""),
    ("其他", "李泽桦(旧账号)", 25, "lzh", "LiZehua", ""),
    ("其他", "林洁", 27, "linjie", "Lin Jie", ""),
    ("其他", "CI/CD Bot", 28, "project_1_bot_416756a64045ea9a8dfd2dc4197e79d4", "Jenkins13", ""),
    ("其他", "陈奕鑫", 19, "chenyx", "Chen Yixin", ""),
    ("其他", "兰输", 20, "lanshu", "Lan Shu", ""),
    ("其他", "曾纪罗", 34, "zengjiluo", "Zeng JiLuo", ""),
    ("其他", "马泽荣", 33, "mazerong", "Ma ZeRong", ""),
    ("其他", "熊定安", 32, "xiongdingan", "Xiong DingAn", ""),
    ("其他", "李嘉俊", 31, "lijj", "Li JiaJun", ""),
    ("其他", "李彧", 37, "liy", "Li Yu", ""),
    ("其他", "何喻尧", 36, "heyuyao", "He YuYao", ""),
    ("其他", "陈诺怡", 38, "chenny", "Chen NuoYi", ""),
    ("其他", "测试账号", 40, "demoAbc", "DemoAbc", ""),
    ("其他", "HK团队", 41, "wcheng", "Wallace CHENG", ""),
    ("其他", "HK团队", 42, "tommy", "Tommy NG", ""),
    ("其他", "HK团队", 43, "leehwh", "Herman LEE", ""),
    ("其他", "HK团队", 44, "cody", "Cody LI", ""),
    ("其他", "HK团队", 45, "kelvin", "Kelvin WONG", ""),
    ("其他", "HK团队", 46, "nichole", "Nichole IP", ""),
    ("其他", "HK团队", 47, "taylor", "Taylor YEUNG", ""),
    ("其他", "胡文豪", 61, "huwh", "Hu Wenhao", ""),
    ("其他", "黄少毅", 62, "huangsy", "Huang ShaoYi", ""),
    ("其他", "丁楷", 63, "dingkai", "Ding Kai", ""),
    ("其他", "杨思逸", 59, "yangsy", "Yang Siyi", ""),
    ("其他", "李棉洪", 60, "limh", "Li MianHong", ""),
    ("其他", "HK团队", 58, "alice", "Alice CHUNG", ""),
    ("其他", "HK团队", 57, "kevin", "Kevin TSANG", ""),
    ("其他", "HK团队", 56, "jefferyleung", "Jeffery LEUNG", ""),
    ("其他", "HK团队", 55, "michael", "Michael LIAN", ""),
    ("其他", "HK团队", 54, "evie", "Evie YEUNG", ""),
    ("其他", "HK团队", 53, "josephine", "Josephine CHEUNG", ""),
    ("其他", "HK团队", 52, "wc.yip", "Wing Cheong YIP", ""),
    ("其他", "徐桐", 67, "xutong", "Xu Tong", ""),
    ("其他", "陈晓虹", 68, "chenxiaohong", "Chen XiaoHong", ""),
    ("其他", "刘清斌", 71, "liuqingbin", "Liu QingBin", ""),
    ("其他", "王子路", 72, "wangzilu", "Wang Zilu", ""),
    ("其他", "李文殿", 73, "liwendian", "Li WenDian", ""),
    ("其他", "杨文帆", 75, "yangwf", "Yang Wenfan", ""),
    ("其他", "谢翠君", 79, "xiecj", "Xie CuiJun", ""),
    ("其他", "何彤昕", 80, "hetongxin", "He TongXin", ""),
    ("其他", "黄柏林", 82, "huangbolin", "Huang BoLin", ""),
    ("其他", "尚喻", 83, "shangyu", "Shang Yu", ""),
    ("其他", "杜纪雄", 84, "dujixiong", "Du JiXiong", ""),
    ("其他", "肖泽鑫", 85, "xiaozx", "Xiao Zexin", ""),
    ("其他", "谢翠君2026", 87, "cuicui", "Xie CuiJun2026", ""),
    ("其他", "李媛媛", 88, "liyy", "Li Yuanyuan", ""),
    ("其他", "项目只读Bot", 89, "project_4_bot_03779524c49d69d975bf0a55a296e8e3", "ONLY_READ", ""),
    ("其他", "赵泉凯", 90, "zhaoqk", "Zhao Quankai", ""),
]

# username → 中文名 查找表
USERNAME_TO_CN = {u[3]: u[1] for u in GITLAB_USERS}

# id → 中文名 查找表
ID_TO_CN = {u[2]: u[1] for u in GITLAB_USERS}
